version: "3.8"
services:
  vscode:
    build:
      context: '.'
      dockerfile: "./Dockerfile"
    volumes:
      - ../:/project
    security_opt:
      - seccomp:unconfined
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"